version: "3.2"
services:
  node:
    image: "node:latest"
    user: "node"
    working_dir: /home/node/
    environment:
      - NODE_ENV=development
    volumes:
      - ./server:/home/node/
    networks:
      - frontend
      - backend
    ports:
      - "9001:9001"
    command: "npm run dev"
    container_name: webpackdevserver
  php:
    build: 
      context: './php/'
      args:
       PHP_VERSION: ${PHP_VERSION}
    networks:
      - backend
    volumes:
      - ./:/var/www/html/
    container_name: php
  apache:
    build:
      context: './apache/'
      args:
       APACHE_VERSION: ${APACHE_VERSION}
    depends_on:
      - php
      - db
    networks:
      - frontend
      - backend
    ports:
      - "8080:80"
      - "443:443"
    volumes:
      - ./:/usr/local/apache2/htdocs/
    container_name: apache
  db:
    image: mariadb:latest
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - "9997:3306"
    volumes:
      - ./mariadb/data:/var/lib/mysql
      - ./mariadb/config:/etc/mysql/conf.d
      - ./mariadb/sqlinit:/docker-entrypoint-initdb.d
    networks:
      - backend
    environment:
      MYSQL_ROOT_PASSWORD: "${DB_ROOT_PASSWORD}"
    container_name: mariadb
  adminer:
    image: adminer
    ports:
    - 9996:8080
    networks:
      - backend   
    container_name: adminer    
networks:
  frontend:
  backend:
